version: "3.8"

services:
  mongo:
    image: mongo:6.0.5
    restart: unless-stopped
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"

  elasticsearch:
    image: elasticsearch:8.6.2
    restart: unless-stopped
    env_file: .env
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "--silent",
          "--fail",
          "http://localhost:9200/_cluster/health?wait_for_status=yellow&timeout=5s"
        ]
      interval: 10s
      timeout: 5s
      retries: 5

  kibana:
    image: kibana:8.6.2
    restart: unless-stopped
    env_file: .env
    volumes:
      - kibana_data:/usr/share/kibana/data
    depends_on:
      elasticsearch:
        condition: service_healthy
    ports:
      - "5601:5601"

  web:
    build: .
    env_file: .env
    volumes:
      - .:/home/app/web
    depends_on:
      mongo:
        condition: service_started
      elasticsearch:
        condition: service_healthy
      kibana:
        condition: service_started
    ports:
      - "8000:8000"

volumes:
  mongo_data:
    driver: local
  elasticsearch_data:
    driver: local
  kibana_data:
    driver: local
