version: "3.8"

services:
  elasticsearch:
    image: elasticsearch:8.6.2
    restart: unless-stopped
    environment:
      - logger.level=warn
      - discovery.type=single-node
      - xpack.security.enabled=false
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"

  kibana:
    image: kibana:8.6.2
    restart: unless-stopped
    environment:
      - SERVER_NAME=kibana.local
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    volumes:
      - kibana_data:/usr/share/kibana/data
    depends_on:
      - elasticsearch
    ports:
      - "5601:5601"

  web:
    build: .
    env_file: .env
    volumes:
      - .:/code
    depends_on:
      - elasticsearch
      - kibana
    ports:
      - "8000:8000"

volumes:
  elasticsearch_data:
    driver: local
  kibana_data:
    driver: local
