version: "3.8"

services:
  redis_tests:
    image: redis:7-alpine
    volumes:
      - redis_tests_data:/data
    ports:
      - "6379:6379"

  mongo_tests:
    image: mongo:6.0.5
    restart: unless-stopped
    env_file: .env.tests
    command: ["--auth"]
    volumes:
      - mongo_tests_data:/data/db
    ports:
      - "27017:27017"

  elasticsearch_tests:
    image: elasticsearch:8.6.2
    restart: unless-stopped
    env_file: .env.tests
    volumes:
      - elasticsearch_tests_data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "--silent",
          "--fail",
          "http://localhost:9200/_cluster/health?wait_for_status=yellow&timeout=5s"
        ]
      interval: 5s
      timeout: 5s
      retries: 10

  kibana_tests:
    image: kibana:8.6.2
    restart: unless-stopped
    env_file: .env.tests
    depends_on:
      elasticsearch_tests:
        condition: service_healthy
    ports:
      - "5601:5601"

  web_tests:
    build: .
    env_file: .env.tests
    command:
      [
        "gunicorn",
        "-b",
        "0.0.0.0",
        "-w",
        "4",
        "-k",
        "uvicorn.workers.UvicornWorker",
        "app.main:app"
      ]
    volumes:
      - .:/home/app/web
    depends_on:
      mongo_tests:
        condition: service_started
      elasticsearch_tests:
        condition: service_healthy
      kibana_tests:
        condition: service_started
    ports:
      - "8000:8000"

  worker_tests:
    build: .
    env_file: .env.tests
    command: [ "python", "-m", "app.worker" ]
    volumes:
      - .:/home/app/web
    depends_on:
      redis_tests:
        condition: service_started
      mongo_tests:
        condition: service_started
      elasticsearch_tests:
        condition: service_healthy

volumes:
  redis_tests_data:
    driver: local
  mongo_tests_data:
    driver: local
  elasticsearch_tests_data:
    driver: local
