version: "3.8"

services:
  redis:
    image: redis:7-alpine
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"

  mongo:
    image: mongo:6.0.5
    restart: unless-stopped
    env_file: .env
    command: ["--auth"]
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"

  elasticsearch:
    image: elasticsearch:8.6.2
    restart: unless-stopped
    env_file: .env
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "--silent",
          "--fail",
          "http://localhost:9200/_cluster/health?wait_for_status=yellow&timeout=5s"
        ]
      interval: 5s
      timeout: 5s
      retries: 10

  kibana:
    image: kibana:8.6.2
    restart: unless-stopped
    env_file: .env
    depends_on:
      elasticsearch:
        condition: service_healthy
    ports:
      - "5601:5601"

  web:
    build: .
    env_file: .env
    command:
      [
        "gunicorn",
        "-b",
        "0.0.0.0",
        "-w",
        "4",
        "-k",
        "uvicorn.workers.UvicornWorker",
        "app.main:app"
      ]
    volumes:
      - .:/home/app/web
    depends_on:
      mongo:
        condition: service_started
      elasticsearch:
        condition: service_healthy
      kibana:
        condition: service_started
    ports:
      - "8000:8000"

  worker:
    build: .
    env_file: .env
    command: [ "python", "-m", "app.worker" ]
    volumes:
      - .:/home/app/web
    depends_on:
      redis:
        condition: service_started
      mongo:
        condition: service_started
      elasticsearch:
        condition: service_healthy

volumes:
  redis_data:
    driver: local
  mongo_data:
    driver: local
  elasticsearch_data:
    driver: local
