apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: jelly
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: web
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
      containers:
        - name: web
          image: spyker77/jelly
          command:
            [
              "gunicorn",
              "-b",
              "0.0.0.0",
              "-w",
              "4",
              "-k",
              "uvicorn.workers.UvicornWorker",
              "app.main:app",
            ]
          envFrom:
            - secretRef:
                name: app
          ports:
            - containerPort: 8000
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /graphql
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 1
          readinessProbe:
            httpGet:
              path: /graphql
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 1
