apiVersion: v1
kind: Secret
metadata:
  name: app
  namespace: jelly
type: Opaque
data:
  MONGODB_DATABASE: amVsbHk=
  MONGODB_URL: bW9uZ29kYjovL3Jvb3Q6c2VjcmV0QG1vbmdvLmplbGx5LnN2Yy5jbHVzdGVyLmxvY2FsOjI3MDE3
  ELASTICSEARCH_URL: aHR0cDovL2VsYXN0aWNzZWFyY2guamVsbHkuc3ZjLmNsdXN0ZXIubG9jYWw6OTIwMA==
  REDIS_HOST: cmVkaXMuamVsbHkuc3ZjLmNsdXN0ZXIubG9jYWw=
  REDIS_PORT: NjM3OQ==
---
apiVersion: v1
kind: Secret
metadata:
  name: elasticsearch
  namespace: jelly
type: Opaque
data:
  xpack.security.enabled: ZmFsc2U=
  xpack.security.transport.ssl.enabled: ZmFsc2U=
  xpack.security.http.ssl.enabled: ZmFsc2U=
  discovery.seed_hosts: ZWxhc3RpY3NlYXJjaC5qZWxseS5zdmMuY2x1c3Rlci5sb2NhbA==
  cluster.initial_master_nodes: ZWxhc3RpY3NlYXJjaC0wLGVsYXN0aWNzZWFyY2gtMSxlbGFzdGljc2VhcmNoLTI=
  ES_JAVA_OPTS: LVhtczUxMm0gLVhteDUxMm0=
---
apiVersion: v1
kind: Secret
metadata:
  name: kibana
  namespace: jelly
type: Opaque
data:
  SERVER_NAME: a2liYW5hLmplbGx5LnN2Yy5jbHVzdGVyLmxvY2Fs
  ELASTICSEARCH_HOSTS: aHR0cDovL2VsYXN0aWNzZWFyY2guamVsbHkuc3ZjLmNsdXN0ZXIubG9jYWw6OTIwMA==
---
apiVersion: v1
kind: Secret
metadata:
  name: mongo
  namespace: jelly
type: Opaque
data:
  MONGO_INITDB_ROOT_USERNAME: cm9vdA==
  MONGO_INITDB_ROOT_PASSWORD: c2VjcmV0
