apiVersion: v1
kind: Secret
metadata:
  name: web
type: Opaque
data:
  MONGODB_DATABASE: amVsbHk=
  MONGODB_URL: bW9uZ29kYjovL3Jvb3Q6c2VjcmV0QG1vbmdvLXNlcnZpY2U6MjcwMTc=
  ELASTICSEARCH_URL: aHR0cDovL2VsYXN0aWNzZWFyY2g6OTIwMA==
---
apiVersion: v1
kind: Secret
metadata:
  name: kibana
type: Opaque
data:
  SERVER_NAME: a2liYW5hLmxvY2Fs
  ELASTICSEARCH_HOSTS: aHR0cDovL2VsYXN0aWNzZWFyY2g6OTIwMA==
---
apiVersion: v1
kind: Secret
metadata:
  name: mongo
type: Opaque
data:
  MONGO_INITDB_ROOT_USERNAME: cm9vdA==
  MONGO_INITDB_ROOT_PASSWORD: c2VjcmV0
