name: Continuous Integration

on: [push]

jobs:
  test:
    name: Run through the quality gates
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build and run containers
        run: docker-compose up -d

      - name: Black
        run: docker-compose exec -T web black . --check

      - name: isort
        run: docker-compose exec -T web isort . --check-only

      - name: Flake8
        run: docker-compose exec -T web flake8 .

      - name: Pytest
        run: docker-compose exec -T web pytest .
