name: Continuous Integration

on: [push]

jobs:
  test:
    name: Run through the quality gates
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Black
        run: black . --check

      - name: isort
        run: isort . --check-only

      - name: Flake8
        run: flake8 .

      - name: Pytest
        run: pytest .
